/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AnswerDetail = {
    Auto: 'auto',
    Short: 'short',
    Standard: 'standard',
    Detailed: 'detailed'
} as const;
export type AnswerDetail = typeof AnswerDetail[keyof typeof AnswerDetail];


export function instanceOfAnswerDetail(value: any): boolean {
    for (const key in AnswerDetail) {
        if (Object.prototype.hasOwnProperty.call(AnswerDetail, key)) {
            if (AnswerDetail[key as keyof typeof AnswerDetail] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AnswerDetailFromJSON(json: any): AnswerDetail {
    return AnswerDetailFromJSONTyped(json, false);
}

export function AnswerDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerDetail {
    return json as AnswerDetail;
}

export function AnswerDetailToJSON(value?: AnswerDetail | null): any {
    return value as any;
}

export function AnswerDetailToJSONTyped(value: any, ignoreDiscriminator: boolean): AnswerDetail {
    return value as AnswerDetail;
}

