/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatHistoryMessage
 */
export interface ChatHistoryMessage {
    /**
     * 
     * @type {ChatHistoryMessageRoleEnum}
     * @memberof ChatHistoryMessage
     */
    role: ChatHistoryMessageRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ChatHistoryMessage
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ChatHistoryMessage
     */
    messageId?: string | null;
}


/**
 * @export
 */
export const ChatHistoryMessageRoleEnum = {
    User: 'user',
    Ai: 'ai'
} as const;
export type ChatHistoryMessageRoleEnum = typeof ChatHistoryMessageRoleEnum[keyof typeof ChatHistoryMessageRoleEnum];


/**
 * Check if a given object implements the ChatHistoryMessage interface.
 */
export function instanceOfChatHistoryMessage(value: object): value is ChatHistoryMessage {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ChatHistoryMessageFromJSON(json: any): ChatHistoryMessage {
    return ChatHistoryMessageFromJSONTyped(json, false);
}

export function ChatHistoryMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatHistoryMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
        'content': json['content'],
        'messageId': json['message_id'] === undefined ? undefined : json['message_id'] === null ? null : json['message_id'],
    };
}

export function ChatHistoryMessageToJSON(json: any): ChatHistoryMessage {
    return ChatHistoryMessageToJSONTyped(json, false);
}

export function ChatHistoryMessageToJSONTyped(value?: ChatHistoryMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
        'message_id': value['messageId'],
    };
}

