/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CopilotModel
 */
export interface CopilotModel {
    /**
     * 
     * @type {string}
     * @memberof CopilotModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CopilotModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CopilotModel
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CopilotModel
     */
    priceCategory?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CopilotModel
     */
    maxContextTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CopilotModel
     */
    maxPromptTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CopilotModel
     */
    maxOutputTokens?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotModel
     */
    supportsVision?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotModel
     */
    supportsReasoningEffort?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CopilotModel
     */
    adaptiveThinking?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CopilotModel
     */
    defaultReasoningEffort?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CopilotModel
     */
    supportedReasoningEfforts?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CopilotModel
     */
    policyState?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CopilotModel
     */
    readonly isAuto: boolean;
}

/**
 * Check if a given object implements the CopilotModel interface.
 */
export function instanceOfCopilotModel(value: object): value is CopilotModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('isAuto' in (value as Record<string, any>)) && !('is_auto' in (value as Record<string, any>))) || ((value as Record<string, any>)['isAuto'] === undefined && (value as Record<string, any>)['is_auto'] === undefined)) return false;
    return true;
}

export function CopilotModelFromJSON(json: any): CopilotModel {
    return CopilotModelFromJSONTyped(json, false);
}

export function CopilotModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'category': json['category'] === undefined ? undefined : json['category'] === null ? null : json['category'],
        'priceCategory': json['price_category'] === undefined ? undefined : json['price_category'] === null ? null : json['price_category'],
        'maxContextTokens': json['max_context_tokens'] === undefined ? undefined : json['max_context_tokens'] === null ? null : json['max_context_tokens'],
        'maxPromptTokens': json['max_prompt_tokens'] === undefined ? undefined : json['max_prompt_tokens'] === null ? null : json['max_prompt_tokens'],
        'maxOutputTokens': json['max_output_tokens'] === undefined ? undefined : json['max_output_tokens'] === null ? null : json['max_output_tokens'],
        'supportsVision': json['supports_vision'] === undefined ? undefined : json['supports_vision'] === null ? null : json['supports_vision'],
        'supportsReasoningEffort': json['supports_reasoning_effort'] === undefined ? undefined : json['supports_reasoning_effort'] === null ? null : json['supports_reasoning_effort'],
        'adaptiveThinking': json['adaptive_thinking'] === undefined ? undefined : json['adaptive_thinking'] === null ? null : json['adaptive_thinking'],
        'defaultReasoningEffort': json['default_reasoning_effort'] === undefined ? undefined : json['default_reasoning_effort'] === null ? null : json['default_reasoning_effort'],
        'supportedReasoningEfforts': json['supported_reasoning_efforts'] === undefined ? undefined : json['supported_reasoning_efforts'] === null ? null : json['supported_reasoning_efforts'],
        'policyState': json['policy_state'] === undefined ? undefined : json['policy_state'] === null ? null : json['policy_state'],
        'isAuto': json['is_auto'],
    };
}

export function CopilotModelToJSON(json: any): CopilotModel {
    return CopilotModelToJSONTyped(json, false);
}

export function CopilotModelToJSONTyped(value?: Omit<CopilotModel, 'isAuto'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'category': value['category'],
        'price_category': value['priceCategory'],
        'max_context_tokens': value['maxContextTokens'],
        'max_prompt_tokens': value['maxPromptTokens'],
        'max_output_tokens': value['maxOutputTokens'],
        'supports_vision': value['supportsVision'],
        'supports_reasoning_effort': value['supportsReasoningEffort'],
        'adaptive_thinking': value['adaptiveThinking'],
        'default_reasoning_effort': value['defaultReasoningEffort'],
        'supported_reasoning_efforts': value['supportedReasoningEfforts'],
        'policy_state': value['policyState'],
    };
}

