/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CopilotModel } from './CopilotModel';
import {
    CopilotModelFromJSON,
    CopilotModelFromJSONTyped,
    CopilotModelToJSON,
    CopilotModelToJSONTyped,
} from './CopilotModel';

/**
 * The model a user has selected plus the reasoning effort applied to it.
 * @export
 * @interface CopilotModelSelection
 */
export interface CopilotModelSelection {
    /**
     * 
     * @type {CopilotModel}
     * @memberof CopilotModelSelection
     */
    model: CopilotModel;
    /**
     * 
     * @type {string}
     * @memberof CopilotModelSelection
     */
    reasoningEffort?: string | null;
}

/**
 * Check if a given object implements the CopilotModelSelection interface.
 */
export function instanceOfCopilotModelSelection(value: object): value is CopilotModelSelection {
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function CopilotModelSelectionFromJSON(json: any): CopilotModelSelection {
    return CopilotModelSelectionFromJSONTyped(json, false);
}

export function CopilotModelSelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopilotModelSelection {
    if (json == null) {
        return json;
    }
    return {
        
        'model': CopilotModelFromJSON(json['model']),
        'reasoningEffort': json['reasoning_effort'] === undefined ? undefined : json['reasoning_effort'] === null ? null : json['reasoning_effort'],
    };
}

export function CopilotModelSelectionToJSON(json: any): CopilotModelSelection {
    return CopilotModelSelectionToJSONTyped(json, false);
}

export function CopilotModelSelectionToJSONTyped(value?: CopilotModelSelection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': CopilotModelToJSON(value['model']),
        'reasoning_effort': value['reasoningEffort'],
    };
}

