/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomFields
 */
export interface CustomFields {
    /**
     * 
     * @type {string}
     * @memberof CustomFields
     */
    safetyRequirement?: string | null;
}

/**
 * Check if a given object implements the CustomFields interface.
 */
export function instanceOfCustomFields(value: object): value is CustomFields {
    return true;
}

export function CustomFieldsFromJSON(json: any): CustomFields {
    return CustomFieldsFromJSONTyped(json, false);
}

export function CustomFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomFields {
    if (json == null) {
        return json;
    }
    return {
        
        'safetyRequirement': json['safety_requirement'] === undefined ? undefined : json['safety_requirement'] === null ? null : json['safety_requirement'],
    };
}

export function CustomFieldsToJSON(json: any): CustomFields {
    return CustomFieldsToJSONTyped(json, false);
}

export function CustomFieldsToJSONTyped(value?: CustomFields | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'safety_requirement': value['safetyRequirement'],
    };
}

