/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomFields
 */
export interface CustomFields {
    /**
     * 
     * @type {CustomFieldsWorkitemTypeEnum}
     * @memberof CustomFields
     */
    workitemType: CustomFieldsWorkitemTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomFields
     */
    priority?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomFields
     */
    severity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomFields
     */
    author?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomFields
     */
    assignee?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CustomFields
     */
    created?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CustomFields
     */
    updated?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CustomFields
     */
    dueDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CustomFields
     */
    safetyClass?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomFields
     */
    requirementCategory?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomFields
     */
    tags?: Array<string>;
}


/**
 * @export
 */
export const CustomFieldsWorkitemTypeEnum = {
    Requirement: 'requirement',
    Defect: 'defect',
    Testcase: 'testcase',
    Task: 'task',
    ChangeRequest: 'change_request',
    Risk: 'risk'
} as const;
export type CustomFieldsWorkitemTypeEnum = typeof CustomFieldsWorkitemTypeEnum[keyof typeof CustomFieldsWorkitemTypeEnum];


/**
 * Check if a given object implements the CustomFields interface.
 */
export function instanceOfCustomFields(value: object): value is CustomFields {
    if ((!('workitemType' in (value as Record<string, any>)) && !('workitem_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['workitemType'] === undefined && (value as Record<string, any>)['workitem_type'] === undefined)) return false;
    return true;
}

export function CustomFieldsFromJSON(json: any): CustomFields {
    return CustomFieldsFromJSONTyped(json, false);
}

export function CustomFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomFields {
    if (json == null) {
        return json;
    }
    return {
        
        'workitemType': json['workitem_type'],
        'priority': json['priority'] === undefined ? undefined : json['priority'] === null ? null : json['priority'],
        'severity': json['severity'] === undefined ? undefined : json['severity'] === null ? null : json['severity'],
        'author': json['author'] === undefined ? undefined : json['author'] === null ? null : json['author'],
        'assignee': json['assignee'] === undefined ? undefined : json['assignee'] === null ? null : json['assignee'],
        'created': json['created'] === undefined ? undefined : json['created'] === null ? null : (new Date(json['created'])),
        'updated': json['updated'] === undefined ? undefined : json['updated'] === null ? null : (new Date(json['updated'])),
        'dueDate': json['due_date'] === undefined ? undefined : json['due_date'] === null ? null : (new Date(json['due_date'])),
        'safetyClass': json['safety_class'] === undefined ? undefined : json['safety_class'] === null ? null : json['safety_class'],
        'requirementCategory': json['requirement_category'] === undefined ? undefined : json['requirement_category'] === null ? null : json['requirement_category'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function CustomFieldsToJSON(json: any): CustomFields {
    return CustomFieldsToJSONTyped(json, false);
}

export function CustomFieldsToJSONTyped(value?: CustomFields | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workitem_type': value['workitemType'],
        'priority': value['priority'],
        'severity': value['severity'],
        'author': value['author'],
        'assignee': value['assignee'],
        'created': value['created'] == null ? value['created'] : value['created'].toISOString(),
        'updated': value['updated'] == null ? value['updated'] : value['updated'].toISOString(),
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
        'safety_class': value['safetyClass'],
        'requirement_category': value['requirementCategory'],
        'tags': value['tags'],
    };
}

