/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitHubAiModel
 */
export interface GitHubAiModel {
    /**
     * 
     * @type {string}
     * @memberof GitHubAiModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GitHubAiModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GitHubAiModel
     */
    publisher: string;
    /**
     * 
     * @type {string}
     * @memberof GitHubAiModel
     */
    registry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GitHubAiModel
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GitHubAiModel
     */
    htmlUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GitHubAiModel
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GitHubAiModel
     */
    rateLimitTier: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GitHubAiModel
     */
    capabilities?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GitHubAiModel
     */
    supportedInputModalities?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GitHubAiModel
     */
    supportedOutputModalities?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GitHubAiModel
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the GitHubAiModel interface.
 */
export function instanceOfGitHubAiModel(value: object): value is GitHubAiModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('publisher' in value) || value['publisher'] === undefined) return false;
    if ((!('rateLimitTier' in (value as Record<string, any>)) && !('rate_limit_tier' in (value as Record<string, any>))) || ((value as Record<string, any>)['rateLimitTier'] === undefined && (value as Record<string, any>)['rate_limit_tier'] === undefined)) return false;
    return true;
}

export function GitHubAiModelFromJSON(json: any): GitHubAiModel {
    return GitHubAiModelFromJSONTyped(json, false);
}

export function GitHubAiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitHubAiModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'publisher': json['publisher'],
        'registry': json['registry'] === undefined ? undefined : json['registry'] === null ? null : json['registry'],
        'summary': json['summary'] === undefined ? undefined : json['summary'] === null ? null : json['summary'],
        'htmlUrl': json['html_url'] === undefined ? undefined : json['html_url'] === null ? null : json['html_url'],
        'version': json['version'] === undefined ? undefined : json['version'] === null ? null : json['version'],
        'rateLimitTier': json['rate_limit_tier'],
        'capabilities': json['capabilities'] == null ? undefined : json['capabilities'],
        'supportedInputModalities': json['supported_input_modalities'] == null ? undefined : json['supported_input_modalities'],
        'supportedOutputModalities': json['supported_output_modalities'] == null ? undefined : json['supported_output_modalities'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function GitHubAiModelToJSON(json: any): GitHubAiModel {
    return GitHubAiModelToJSONTyped(json, false);
}

export function GitHubAiModelToJSONTyped(value?: GitHubAiModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'publisher': value['publisher'],
        'registry': value['registry'],
        'summary': value['summary'],
        'html_url': value['htmlUrl'],
        'version': value['version'],
        'rate_limit_tier': value['rateLimitTier'],
        'capabilities': value['capabilities'],
        'supported_input_modalities': value['supportedInputModalities'],
        'supported_output_modalities': value['supportedOutputModalities'],
        'tags': value['tags'],
    };
}

