/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestResponse
 */
export interface IngestResponse {
    /**
     * 
     * @type {string}
     * @memberof IngestResponse
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof IngestResponse
     */
    ingestedItems: number;
}

/**
 * Check if a given object implements the IngestResponse interface.
 */
export function instanceOfIngestResponse(value: object): value is IngestResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('ingestedItems' in (value as Record<string, any>)) && !('ingested_items' in (value as Record<string, any>))) || ((value as Record<string, any>)['ingestedItems'] === undefined && (value as Record<string, any>)['ingested_items'] === undefined)) return false;
    return true;
}

export function IngestResponseFromJSON(json: any): IngestResponse {
    return IngestResponseFromJSONTyped(json, false);
}

export function IngestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'ingestedItems': json['ingested_items'],
    };
}

export function IngestResponseToJSON(json: any): IngestResponse {
    return IngestResponseToJSONTyped(json, false);
}

export function IngestResponseToJSONTyped(value?: IngestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'ingested_items': value['ingestedItems'],
    };
}

