/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkedWorkItem
 */
export interface LinkedWorkItem {
    /**
     * 
     * @type {string}
     * @memberof LinkedWorkItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LinkedWorkItem
     */
    role: string;
    /**
     * 
     * @type {LinkedWorkItemDirectionEnum}
     * @memberof LinkedWorkItem
     */
    direction: LinkedWorkItemDirectionEnum;
}


/**
 * @export
 */
export const LinkedWorkItemDirectionEnum = {
    Outgoing: 'outgoing',
    Incoming: 'incoming'
} as const;
export type LinkedWorkItemDirectionEnum = typeof LinkedWorkItemDirectionEnum[keyof typeof LinkedWorkItemDirectionEnum];


/**
 * Check if a given object implements the LinkedWorkItem interface.
 */
export function instanceOfLinkedWorkItem(value: object): value is LinkedWorkItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    return true;
}

export function LinkedWorkItemFromJSON(json: any): LinkedWorkItem {
    return LinkedWorkItemFromJSONTyped(json, false);
}

export function LinkedWorkItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkedWorkItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
        'direction': json['direction'],
    };
}

export function LinkedWorkItemToJSON(json: any): LinkedWorkItem {
    return LinkedWorkItemToJSONTyped(json, false);
}

export function LinkedWorkItemToJSONTyped(value?: LinkedWorkItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'direction': value['direction'],
    };
}

