/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomFields } from './CustomFields';
import {
    CustomFieldsFromJSON,
    CustomFieldsFromJSONTyped,
    CustomFieldsToJSON,
    CustomFieldsToJSONTyped,
} from './CustomFields';
import type { LinkedWorkItem } from './LinkedWorkItem';
import {
    LinkedWorkItemFromJSON,
    LinkedWorkItemFromJSONTyped,
    LinkedWorkItemToJSON,
    LinkedWorkItemToJSONTyped,
} from './LinkedWorkItem';

/**
 * Validated domain representation of a Polarion work item.
 * @export
 * @interface PolarionWorkItem
 */
export interface PolarionWorkItem {
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    workitemId: string;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof PolarionWorkItem
     */
    revision: number;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    status: string;
    /**
     * 
     * @type {Array<LinkedWorkItem>}
     * @memberof PolarionWorkItem
     */
    linkedWorkitems?: Array<LinkedWorkItem>;
    /**
     * 
     * @type {CustomFields}
     * @memberof PolarionWorkItem
     */
    customFields: CustomFields;
}

/**
 * Check if a given object implements the PolarionWorkItem interface.
 */
export function instanceOfPolarionWorkItem(value: object): value is PolarionWorkItem {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if ((!('workitemId' in (value as Record<string, any>)) && !('workitem_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['workitemId'] === undefined && (value as Record<string, any>)['workitem_id'] === undefined)) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('customFields' in (value as Record<string, any>)) && !('custom_fields' in (value as Record<string, any>))) || ((value as Record<string, any>)['customFields'] === undefined && (value as Record<string, any>)['custom_fields'] === undefined)) return false;
    return true;
}

export function PolarionWorkItemFromJSON(json: any): PolarionWorkItem {
    return PolarionWorkItemFromJSONTyped(json, false);
}

export function PolarionWorkItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolarionWorkItem {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'workitemId': json['workitem_id'],
        'title': json['title'],
        'text': json['text'],
        'revision': json['revision'],
        'status': json['status'],
        'linkedWorkitems': json['linked_workitems'] == null ? undefined : ((json['linked_workitems'] as Array<any>).map(LinkedWorkItemFromJSON)),
        'customFields': CustomFieldsFromJSON(json['custom_fields']),
    };
}

export function PolarionWorkItemToJSON(json: any): PolarionWorkItem {
    return PolarionWorkItemToJSONTyped(json, false);
}

export function PolarionWorkItemToJSONTyped(value?: PolarionWorkItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'workitem_id': value['workitemId'],
        'title': value['title'],
        'text': value['text'],
        'revision': value['revision'],
        'status': value['status'],
        'linked_workitems': value['linkedWorkitems'] == null ? undefined : ((value['linkedWorkitems'] as Array<any>).map(LinkedWorkItemToJSON)),
        'custom_fields': CustomFieldsToJSON(value['customFields']),
    };
}

