/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolarionDocumentMetadata
 */
export interface PolarionDocumentMetadata {
    /**
     * 
     * @type {string}
     * @memberof PolarionDocumentMetadata
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PolarionDocumentMetadata
     */
    category: string;
}

/**
 * Check if a given object implements the PolarionDocumentMetadata interface.
 */
export function instanceOfPolarionDocumentMetadata(value: object): value is PolarionDocumentMetadata {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function PolarionDocumentMetadataFromJSON(json: any): PolarionDocumentMetadata {
    return PolarionDocumentMetadataFromJSONTyped(json, false);
}

export function PolarionDocumentMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolarionDocumentMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'category': json['category'],
    };
}

export function PolarionDocumentMetadataToJSON(json: any): PolarionDocumentMetadata {
    return PolarionDocumentMetadataToJSONTyped(json, false);
}

export function PolarionDocumentMetadataToJSONTyped(value?: PolarionDocumentMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'category': value['category'],
    };
}

