/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolarionDocumentMetadata } from './PolarionDocumentMetadata';
import {
    PolarionDocumentMetadataFromJSON,
    PolarionDocumentMetadataFromJSONTyped,
    PolarionDocumentMetadataToJSON,
    PolarionDocumentMetadataToJSONTyped,
} from './PolarionDocumentMetadata';

/**
 * 
 * @export
 * @interface PolarionProjectMetadata
 */
export interface PolarionProjectMetadata {
    /**
     * 
     * @type {string}
     * @memberof PolarionProjectMetadata
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PolarionProjectMetadata
     */
    contexts: Array<string>;
    /**
     * 
     * @type {Array<PolarionDocumentMetadata>}
     * @memberof PolarionProjectMetadata
     */
    documents: Array<PolarionDocumentMetadata>;
}

/**
 * Check if a given object implements the PolarionProjectMetadata interface.
 */
export function instanceOfPolarionProjectMetadata(value: object): value is PolarionProjectMetadata {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contexts' in value) || value['contexts'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function PolarionProjectMetadataFromJSON(json: any): PolarionProjectMetadata {
    return PolarionProjectMetadataFromJSONTyped(json, false);
}

export function PolarionProjectMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolarionProjectMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'contexts': json['contexts'],
        'documents': ((json['documents'] as Array<any>).map(PolarionDocumentMetadataFromJSON)),
    };
}

export function PolarionProjectMetadataToJSON(json: any): PolarionProjectMetadata {
    return PolarionProjectMetadataToJSONTyped(json, false);
}

export function PolarionProjectMetadataToJSONTyped(value?: PolarionProjectMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'contexts': value['contexts'],
        'documents': ((value['documents'] as Array<any>).map(PolarionDocumentMetadataToJSON)),
    };
}

