/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolarionImportStatus
 */
export interface PolarionImportStatus {
    /**
     * 
     * @type {string}
     * @memberof PolarionImportStatus
     */
    collectionName: string;
    /**
     * 
     * @type {Date}
     * @memberof PolarionImportStatus
     */
    completedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof PolarionImportStatus
     */
    processedItems: number;
}

/**
 * Check if a given object implements the PolarionImportStatus interface.
 */
export function instanceOfPolarionImportStatus(value: object): value is PolarionImportStatus {
    if ((!('collectionName' in (value as Record<string, any>)) && !('collection_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['collectionName'] === undefined && (value as Record<string, any>)['collection_name'] === undefined)) return false;
    if ((!('completedAt' in (value as Record<string, any>)) && !('completed_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['completedAt'] === undefined && (value as Record<string, any>)['completed_at'] === undefined)) return false;
    if ((!('processedItems' in (value as Record<string, any>)) && !('processed_items' in (value as Record<string, any>))) || ((value as Record<string, any>)['processedItems'] === undefined && (value as Record<string, any>)['processed_items'] === undefined)) return false;
    return true;
}

export function PolarionImportStatusFromJSON(json: any): PolarionImportStatus {
    return PolarionImportStatusFromJSONTyped(json, false);
}

export function PolarionImportStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolarionImportStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionName': json['collection_name'],
        'completedAt': (new Date(json['completed_at'])),
        'processedItems': json['processed_items'],
    };
}

export function PolarionImportStatusToJSON(json: any): PolarionImportStatus {
    return PolarionImportStatusToJSONTyped(json, false);
}

export function PolarionImportStatusToJSONTyped(value?: PolarionImportStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection_name': value['collectionName'],
        'completed_at': value['completedAt'].toISOString(),
        'processed_items': value['processedItems'],
    };
}

