/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomFields } from './CustomFields';
import {
    CustomFieldsFromJSON,
    CustomFieldsFromJSONTyped,
    CustomFieldsToJSON,
    CustomFieldsToJSONTyped,
} from './CustomFields';
import type { LinkedWorkItem } from './LinkedWorkItem';
import {
    LinkedWorkItemFromJSON,
    LinkedWorkItemFromJSONTyped,
    LinkedWorkItemToJSON,
    LinkedWorkItemToJSONTyped,
} from './LinkedWorkItem';

/**
 * Validated domain representation of a Polarion work item.
 * @export
 * @interface PolarionWorkItem
 */
export interface PolarionWorkItem {
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    projectName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    workItemId: string;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    workItemType: string;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    documentName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PolarionWorkItem
     */
    revision: number;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PolarionWorkItem
     */
    location?: string | null;
    /**
     * 
     * @type {Array<LinkedWorkItem>}
     * @memberof PolarionWorkItem
     */
    linkedWorkItems?: Array<LinkedWorkItem>;
    /**
     * 
     * @type {CustomFields}
     * @memberof PolarionWorkItem
     */
    customFields?: CustomFields;
}

/**
 * Check if a given object implements the PolarionWorkItem interface.
 */
export function instanceOfPolarionWorkItem(value: object): value is PolarionWorkItem {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if ((!('workItemId' in (value as Record<string, any>)) && !('work_item_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['workItemId'] === undefined && (value as Record<string, any>)['work_item_id'] === undefined)) return false;
    if ((!('workItemType' in (value as Record<string, any>)) && !('work_item_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['workItemType'] === undefined && (value as Record<string, any>)['work_item_type'] === undefined)) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function PolarionWorkItemFromJSON(json: any): PolarionWorkItem {
    return PolarionWorkItemFromJSONTyped(json, false);
}

export function PolarionWorkItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolarionWorkItem {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'projectName': json['project_name'] === undefined ? undefined : json['project_name'] === null ? null : json['project_name'],
        'workItemId': json['work_item_id'],
        'workItemType': json['work_item_type'],
        'documentName': json['document_name'] === undefined ? undefined : json['document_name'] === null ? null : json['document_name'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'revision': json['revision'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : json['status'],
        'location': json['location'] === undefined ? undefined : json['location'] === null ? null : json['location'],
        'linkedWorkItems': json['linked_work_items'] == null ? undefined : ((json['linked_work_items'] as Array<any>).map(LinkedWorkItemFromJSON)),
        'customFields': json['custom_fields'] == null ? undefined : CustomFieldsFromJSON(json['custom_fields']),
    };
}

export function PolarionWorkItemToJSON(json: any): PolarionWorkItem {
    return PolarionWorkItemToJSONTyped(json, false);
}

export function PolarionWorkItemToJSONTyped(value?: PolarionWorkItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'project_name': value['projectName'],
        'work_item_id': value['workItemId'],
        'work_item_type': value['workItemType'],
        'document_name': value['documentName'],
        'title': value['title'],
        'description': value['description'],
        'revision': value['revision'],
        'status': value['status'],
        'location': value['location'],
        'linked_work_items': value['linkedWorkItems'] == null ? undefined : ((value['linkedWorkItems'] as Array<any>).map(LinkedWorkItemToJSON)),
        'custom_fields': CustomFieldsToJSON(value['customFields']),
    };
}

