/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolarionProjectMetadata } from './PolarionProjectMetadata';
import {
    PolarionProjectMetadataFromJSON,
    PolarionProjectMetadataFromJSONTyped,
    PolarionProjectMetadataToJSON,
    PolarionProjectMetadataToJSONTyped,
} from './PolarionProjectMetadata';

/**
 * 
 * @export
 * @interface PolarionMetadataResponse
 */
export interface PolarionMetadataResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof PolarionMetadataResponse
     */
    projectIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PolarionMetadataResponse
     */
    projectContexts: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PolarionMetadataResponse
     */
    projectCategories: Array<string>;
    /**
     * 
     * @type {Array<PolarionProjectMetadata>}
     * @memberof PolarionMetadataResponse
     */
    projects: Array<PolarionProjectMetadata>;
}

/**
 * Check if a given object implements the PolarionMetadataResponse interface.
 */
export function instanceOfPolarionMetadataResponse(value: object): value is PolarionMetadataResponse {
    if ((!('projectIds' in (value as Record<string, any>)) && !('project_ids' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectIds'] === undefined && (value as Record<string, any>)['project_ids'] === undefined)) return false;
    if ((!('projectContexts' in (value as Record<string, any>)) && !('project_contexts' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectContexts'] === undefined && (value as Record<string, any>)['project_contexts'] === undefined)) return false;
    if ((!('projectCategories' in (value as Record<string, any>)) && !('project_categories' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectCategories'] === undefined && (value as Record<string, any>)['project_categories'] === undefined)) return false;
    if (!('projects' in value) || value['projects'] === undefined) return false;
    return true;
}

export function PolarionMetadataResponseFromJSON(json: any): PolarionMetadataResponse {
    return PolarionMetadataResponseFromJSONTyped(json, false);
}

export function PolarionMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolarionMetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'projectIds': json['project_ids'],
        'projectContexts': json['project_contexts'],
        'projectCategories': json['project_categories'],
        'projects': ((json['projects'] as Array<any>).map(PolarionProjectMetadataFromJSON)),
    };
}

export function PolarionMetadataResponseToJSON(json: any): PolarionMetadataResponse {
    return PolarionMetadataResponseToJSONTyped(json, false);
}

export function PolarionMetadataResponseToJSONTyped(value?: PolarionMetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_ids': value['projectIds'],
        'project_contexts': value['projectContexts'],
        'project_categories': value['projectCategories'],
        'projects': ((value['projects'] as Array<any>).map(PolarionProjectMetadataToJSON)),
    };
}

