/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectImportConfig } from './ProjectImportConfig';
import {
    ProjectImportConfigFromJSON,
    ProjectImportConfigFromJSONTyped,
    ProjectImportConfigToJSON,
    ProjectImportConfigToJSONTyped,
} from './ProjectImportConfig';

/**
 * 
 * @export
 * @interface PolarionImportConfig
 */
export interface PolarionImportConfig {
    /**
     * 
     * @type {number}
     * @memberof PolarionImportConfig
     */
    schemaVersion?: number;
    /**
     * 
     * @type {Array<ProjectImportConfig>}
     * @memberof PolarionImportConfig
     */
    projects: Array<ProjectImportConfig>;
}

/**
 * Check if a given object implements the PolarionImportConfig interface.
 */
export function instanceOfPolarionImportConfig(value: object): value is PolarionImportConfig {
    if (!('projects' in value) || value['projects'] === undefined) return false;
    return true;
}

export function PolarionImportConfigFromJSON(json: any): PolarionImportConfig {
    return PolarionImportConfigFromJSONTyped(json, false);
}

export function PolarionImportConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolarionImportConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schema_version'] == null ? undefined : json['schema_version'],
        'projects': ((json['projects'] as Array<any>).map(ProjectImportConfigFromJSON)),
    };
}

export function PolarionImportConfigToJSON(json: any): PolarionImportConfig {
    return PolarionImportConfigToJSONTyped(json, false);
}

export function PolarionImportConfigToJSONTyped(value?: PolarionImportConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schema_version': value['schemaVersion'],
        'projects': ((value['projects'] as Array<any>).map(ProjectImportConfigToJSON)),
    };
}

