/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkItemImportConfig } from './WorkItemImportConfig';
import {
    WorkItemImportConfigFromJSON,
    WorkItemImportConfigFromJSONTyped,
    WorkItemImportConfigToJSON,
    WorkItemImportConfigToJSONTyped,
} from './WorkItemImportConfig';
import type { ProjectDocument } from './ProjectDocument';
import {
    ProjectDocumentFromJSON,
    ProjectDocumentFromJSONTyped,
    ProjectDocumentToJSON,
    ProjectDocumentToJSONTyped,
} from './ProjectDocument';

/**
 * 
 * @export
 * @interface ProjectImportConfig
 */
export interface ProjectImportConfig {
    /**
     * 
     * @type {string}
     * @memberof ProjectImportConfig
     */
    projectId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectImportConfig
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectImportConfig
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectImportConfig
     */
    projectContext: Array<string>;
    /**
     * 
     * @type {Array<ProjectDocument>}
     * @memberof ProjectImportConfig
     */
    documents: Array<ProjectDocument>;
    /**
     * 
     * @type {WorkItemImportConfig}
     * @memberof ProjectImportConfig
     */
    workItems: WorkItemImportConfig;
}

/**
 * Check if a given object implements the ProjectImportConfig interface.
 */
export function instanceOfProjectImportConfig(value: object): value is ProjectImportConfig {
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('projectContext' in (value as Record<string, any>)) && !('project_context' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectContext'] === undefined && (value as Record<string, any>)['project_context'] === undefined)) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    if ((!('workItems' in (value as Record<string, any>)) && !('work_items' in (value as Record<string, any>))) || ((value as Record<string, any>)['workItems'] === undefined && (value as Record<string, any>)['work_items'] === undefined)) return false;
    return true;
}

export function ProjectImportConfigFromJSON(json: any): ProjectImportConfig {
    return ProjectImportConfigFromJSONTyped(json, false);
}

export function ProjectImportConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectImportConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'description': json['description'],
        'projectContext': json['project_context'],
        'documents': ((json['documents'] as Array<any>).map(ProjectDocumentFromJSON)),
        'workItems': WorkItemImportConfigFromJSON(json['work_items']),
    };
}

export function ProjectImportConfigToJSON(json: any): ProjectImportConfig {
    return ProjectImportConfigToJSONTyped(json, false);
}

export function ProjectImportConfigToJSONTyped(value?: ProjectImportConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'enabled': value['enabled'],
        'description': value['description'],
        'project_context': value['projectContext'],
        'documents': ((value['documents'] as Array<any>).map(ProjectDocumentToJSON)),
        'work_items': WorkItemImportConfigToJSON(value['workItems']),
    };
}

