/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectDocument
 */
export interface ProjectDocument {
    /**
     * 
     * @type {string}
     * @memberof ProjectDocument
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDocument
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDocument
     */
    language: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDocument
     */
    description: string;
}

/**
 * Check if a given object implements the ProjectDocument interface.
 */
export function instanceOfProjectDocument(value: object): value is ProjectDocument {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ProjectDocumentFromJSON(json: any): ProjectDocument {
    return ProjectDocumentFromJSONTyped(json, false);
}

export function ProjectDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'category': json['category'],
        'language': json['language'],
        'description': json['description'],
    };
}

export function ProjectDocumentToJSON(json: any): ProjectDocument {
    return ProjectDocumentToJSONTyped(json, false);
}

export function ProjectDocumentToJSONTyped(value?: ProjectDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'category': value['category'],
        'language': value['language'],
        'description': value['description'],
    };
}

