/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RelationsConfig
 */
export interface RelationsConfig {
    /**
     * 
     * @type {Array<string>}
     * @memberof RelationsConfig
     */
    fields?: Array<string>;
}

/**
 * Check if a given object implements the RelationsConfig interface.
 */
export function instanceOfRelationsConfig(value: object): value is RelationsConfig {
    return true;
}

export function RelationsConfigFromJSON(json: any): RelationsConfig {
    return RelationsConfigFromJSONTyped(json, false);
}

export function RelationsConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationsConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'fields': json['fields'] == null ? undefined : json['fields'],
    };
}

export function RelationsConfigToJSON(json: any): RelationsConfig {
    return RelationsConfigToJSONTyped(json, false);
}

export function RelationsConfigToJSONTyped(value?: RelationsConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fields': value['fields'],
    };
}

