/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationsConfig } from './RelationsConfig';
import {
    RelationsConfigFromJSON,
    RelationsConfigFromJSONTyped,
    RelationsConfigToJSON,
    RelationsConfigToJSONTyped,
} from './RelationsConfig';

/**
 * 
 * @export
 * @interface WorkItemImportConfig
 */
export interface WorkItemImportConfig {
    /**
     * 
     * @type {string}
     * @memberof WorkItemImportConfig
     */
    query?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkItemImportConfig
     */
    commonFields: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof WorkItemImportConfig
     */
    fieldsByType?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {RelationsConfig}
     * @memberof WorkItemImportConfig
     */
    relations?: RelationsConfig;
}

/**
 * Check if a given object implements the WorkItemImportConfig interface.
 */
export function instanceOfWorkItemImportConfig(value: object): value is WorkItemImportConfig {
    if ((!('commonFields' in (value as Record<string, any>)) && !('common_fields' in (value as Record<string, any>))) || ((value as Record<string, any>)['commonFields'] === undefined && (value as Record<string, any>)['common_fields'] === undefined)) return false;
    return true;
}

export function WorkItemImportConfigFromJSON(json: any): WorkItemImportConfig {
    return WorkItemImportConfigFromJSONTyped(json, false);
}

export function WorkItemImportConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemImportConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] === undefined ? undefined : json['query'] === null ? null : json['query'],
        'commonFields': json['common_fields'],
        'fieldsByType': json['fields_by_type'] == null ? undefined : json['fields_by_type'],
        'relations': json['relations'] == null ? undefined : RelationsConfigFromJSON(json['relations']),
    };
}

export function WorkItemImportConfigToJSON(json: any): WorkItemImportConfig {
    return WorkItemImportConfigToJSONTyped(json, false);
}

export function WorkItemImportConfigToJSONTyped(value?: WorkItemImportConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'common_fields': value['commonFields'],
        'fields_by_type': value['fieldsByType'],
        'relations': RelationsConfigToJSON(value['relations']),
    };
}

