/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkItemSearchHit } from './WorkItemSearchHit';
import {
    WorkItemSearchHitFromJSON,
    WorkItemSearchHitFromJSONTyped,
    WorkItemSearchHitToJSON,
    WorkItemSearchHitToJSONTyped,
} from './WorkItemSearchHit';

/**
 * 
 * @export
 * @interface WorkItemAskResponse
 */
export interface WorkItemAskResponse {
    /**
     * 
     * @type {string}
     * @memberof WorkItemAskResponse
     */
    answer: string;
    /**
     * 
     * @type {number}
     * @memberof WorkItemAskResponse
     */
    tokensSpent: number;
    /**
     * 
     * @type {Array<WorkItemSearchHit>}
     * @memberof WorkItemAskResponse
     */
    workItems: Array<WorkItemSearchHit>;
}

/**
 * Check if a given object implements the WorkItemAskResponse interface.
 */
export function instanceOfWorkItemAskResponse(value: object): value is WorkItemAskResponse {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if ((!('tokensSpent' in (value as Record<string, any>)) && !('tokens_spent' in (value as Record<string, any>))) || ((value as Record<string, any>)['tokensSpent'] === undefined && (value as Record<string, any>)['tokens_spent'] === undefined)) return false;
    if ((!('workItems' in (value as Record<string, any>)) && !('work_items' in (value as Record<string, any>))) || ((value as Record<string, any>)['workItems'] === undefined && (value as Record<string, any>)['work_items'] === undefined)) return false;
    return true;
}

export function WorkItemAskResponseFromJSON(json: any): WorkItemAskResponse {
    return WorkItemAskResponseFromJSONTyped(json, false);
}

export function WorkItemAskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemAskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
        'tokensSpent': json['tokens_spent'],
        'workItems': ((json['work_items'] as Array<any>).map(WorkItemSearchHitFromJSON)),
    };
}

export function WorkItemAskResponseToJSON(json: any): WorkItemAskResponse {
    return WorkItemAskResponseToJSONTyped(json, false);
}

export function WorkItemAskResponseToJSONTyped(value?: WorkItemAskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'tokens_spent': value['tokensSpent'],
        'work_items': ((value['workItems'] as Array<any>).map(WorkItemSearchHitToJSON)),
    };
}

