/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolarionWorkItem } from './PolarionWorkItem';
import {
    PolarionWorkItemFromJSON,
    PolarionWorkItemFromJSONTyped,
    PolarionWorkItemToJSON,
    PolarionWorkItemToJSONTyped,
} from './PolarionWorkItem';

/**
 * 
 * @export
 * @interface WorkItemSearchHit
 */
export interface WorkItemSearchHit {
    /**
     * 
     * @type {PolarionWorkItem}
     * @memberof WorkItemSearchHit
     */
    workItem: PolarionWorkItem;
    /**
     * 
     * @type {number}
     * @memberof WorkItemSearchHit
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof WorkItemSearchHit
     */
    pointId: string;
}

/**
 * Check if a given object implements the WorkItemSearchHit interface.
 */
export function instanceOfWorkItemSearchHit(value: object): value is WorkItemSearchHit {
    if ((!('workItem' in (value as Record<string, any>)) && !('work_item' in (value as Record<string, any>))) || ((value as Record<string, any>)['workItem'] === undefined && (value as Record<string, any>)['work_item'] === undefined)) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if ((!('pointId' in (value as Record<string, any>)) && !('point_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['pointId'] === undefined && (value as Record<string, any>)['point_id'] === undefined)) return false;
    return true;
}

export function WorkItemSearchHitFromJSON(json: any): WorkItemSearchHit {
    return WorkItemSearchHitFromJSONTyped(json, false);
}

export function WorkItemSearchHitFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemSearchHit {
    if (json == null) {
        return json;
    }
    return {
        
        'workItem': PolarionWorkItemFromJSON(json['work_item']),
        'score': json['score'],
        'pointId': json['point_id'],
    };
}

export function WorkItemSearchHitToJSON(json: any): WorkItemSearchHit {
    return WorkItemSearchHitToJSONTyped(json, false);
}

export function WorkItemSearchHitToJSONTyped(value?: WorkItemSearchHit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'work_item': PolarionWorkItemToJSON(value['workItem']),
        'score': value['score'],
        'point_id': value['pointId'],
    };
}

