/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkItemSearchHit } from './WorkItemSearchHit';
import {
    WorkItemSearchHitFromJSON,
    WorkItemSearchHitFromJSONTyped,
    WorkItemSearchHitToJSON,
    WorkItemSearchHitToJSONTyped,
} from './WorkItemSearchHit';

/**
 * 
 * @export
 * @interface WorkItemSearchResponse
 */
export interface WorkItemSearchResponse {
    /**
     * 
     * @type {Array<WorkItemSearchHit>}
     * @memberof WorkItemSearchResponse
     */
    workItems: Array<WorkItemSearchHit>;
}

/**
 * Check if a given object implements the WorkItemSearchResponse interface.
 */
export function instanceOfWorkItemSearchResponse(value: object): value is WorkItemSearchResponse {
    if ((!('workItems' in (value as Record<string, any>)) && !('work_items' in (value as Record<string, any>))) || ((value as Record<string, any>)['workItems'] === undefined && (value as Record<string, any>)['work_items'] === undefined)) return false;
    return true;
}

export function WorkItemSearchResponseFromJSON(json: any): WorkItemSearchResponse {
    return WorkItemSearchResponseFromJSONTyped(json, false);
}

export function WorkItemSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkItemSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workItems': ((json['work_items'] as Array<any>).map(WorkItemSearchHitFromJSON)),
    };
}

export function WorkItemSearchResponseToJSON(json: any): WorkItemSearchResponse {
    return WorkItemSearchResponseToJSONTyped(json, false);
}

export function WorkItemSearchResponseToJSONTyped(value?: WorkItemSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'work_items': ((value['workItems'] as Array<any>).map(WorkItemSearchHitToJSON)),
    };
}

