/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type User,
    UserFromJSON,
    UserToJSON,
} from '../models/User';

export interface GithubLoginRequest {
    selectAccount?: boolean;
}

/**
 * GitHubAuthenticationApi - interface
 * 
 * @export
 * @interface GitHubAuthenticationApiInterface
 */
export interface GitHubAuthenticationApiInterface {
    /**
     * Creates request options for githubLogin without sending the request
     * @param {boolean} [selectAccount] 
     * @throws {RequiredError}
     * @memberof GitHubAuthenticationApiInterface
     */
    githubLoginRequestOpts(requestParameters: GithubLoginRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Github Login
     * @param {boolean} [selectAccount] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitHubAuthenticationApiInterface
     */
    githubLoginRaw(requestParameters: GithubLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Github Login
     */
    githubLogin(requestParameters: GithubLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for githubSwitchAccount without sending the request
     * @throws {RequiredError}
     * @memberof GitHubAuthenticationApiInterface
     */
    githubSwitchAccountRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Github Switch Account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitHubAuthenticationApiInterface
     */
    githubSwitchAccountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Github Switch Account
     */
    githubSwitchAccount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for logout without sending the request
     * @throws {RequiredError}
     * @memberof GitHubAuthenticationApiInterface
     */
    logoutRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitHubAuthenticationApiInterface
     */
    logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Logout
     */
    logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for me without sending the request
     * @throws {RequiredError}
     * @memberof GitHubAuthenticationApiInterface
     */
    meRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitHubAuthenticationApiInterface
     */
    meRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>>;

    /**
     * Me
     */
    me(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

}

/**
 * 
 */
export class GitHubAuthenticationApi extends runtime.BaseAPI implements GitHubAuthenticationApiInterface {

    /**
     * Creates request options for githubLogin without sending the request
     */
    async githubLoginRequestOpts(requestParameters: GithubLoginRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['selectAccount'] != null) {
            queryParameters['select_account'] = requestParameters['selectAccount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github/login`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Github Login
     */
    async githubLoginRaw(requestParameters: GithubLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.githubLoginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Github Login
     */
    async githubLogin(requestParameters: GithubLoginRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.githubLoginRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for githubSwitchAccount without sending the request
     */
    async githubSwitchAccountRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github/switch-account`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Github Switch Account
     */
    async githubSwitchAccountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.githubSwitchAccountRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Github Switch Account
     */
    async githubSwitchAccount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.githubSwitchAccountRaw(initOverrides);
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Logout
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Logout
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for me without sending the request
     */
    async meRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Me
     */
    async meRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.meRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Me
     */
    async me(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.meRaw(initOverrides);
        return await response.value();
    }

}
