/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CopilotModel,
    CopilotModelFromJSON,
    CopilotModelToJSON,
} from '../models/CopilotModel';
import {
    type CopilotModelSelection,
    CopilotModelSelectionFromJSON,
    CopilotModelSelectionToJSON,
} from '../models/CopilotModelSelection';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface SetUserModelRequest {
    modelId: string;
    reasoningEffort?: string | null;
}

/**
 * GitHubModelsApi - interface
 * 
 * @export
 * @interface GitHubModelsApiInterface
 */
export interface GitHubModelsApiInterface {
    /**
     * Creates request options for getModel without sending the request
     * @throws {RequiredError}
     * @memberof GitHubModelsApiInterface
     */
    getModelRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Model
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitHubModelsApiInterface
     */
    getModelRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CopilotModelSelection>>;

    /**
     * Get Model
     */
    getModel(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CopilotModelSelection>;

    /**
     * Creates request options for getUserModels without sending the request
     * @throws {RequiredError}
     * @memberof GitHubModelsApiInterface
     */
    getUserModelsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get User Models
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitHubModelsApiInterface
     */
    getUserModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CopilotModel>>>;

    /**
     * Get User Models
     */
    getUserModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CopilotModel>>;

    /**
     * Creates request options for setUserModel without sending the request
     * @param {string} modelId 
     * @param {string} [reasoningEffort] 
     * @throws {RequiredError}
     * @memberof GitHubModelsApiInterface
     */
    setUserModelRequestOpts(requestParameters: SetUserModelRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Set User Model
     * @param {string} modelId 
     * @param {string} [reasoningEffort] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GitHubModelsApiInterface
     */
    setUserModelRaw(requestParameters: SetUserModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CopilotModelSelection>>;

    /**
     * Set User Model
     */
    setUserModel(requestParameters: SetUserModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CopilotModelSelection>;

}

/**
 * 
 */
export class GitHubModelsApi extends runtime.BaseAPI implements GitHubModelsApiInterface {

    /**
     * Creates request options for getModel without sending the request
     */
    async getModelRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ai/github/model`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Model
     */
    async getModelRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CopilotModelSelection>> {
        const requestOptions = await this.getModelRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CopilotModelSelectionFromJSON(jsonValue));
    }

    /**
     * Get Model
     */
    async getModel(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CopilotModelSelection> {
        const response = await this.getModelRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserModels without sending the request
     */
    async getUserModelsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ai/github/models`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get User Models
     */
    async getUserModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CopilotModel>>> {
        const requestOptions = await this.getUserModelsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CopilotModelFromJSON));
    }

    /**
     * Get User Models
     */
    async getUserModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CopilotModel>> {
        const response = await this.getUserModelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setUserModel without sending the request
     */
    async setUserModelRequestOpts(requestParameters: SetUserModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling setUserModel().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['modelId'] != null) {
            queryParameters['model_id'] = requestParameters['modelId'];
        }

        if (requestParameters['reasoningEffort'] != null) {
            queryParameters['reasoning_effort'] = requestParameters['reasoningEffort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ai/github/model`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Set User Model
     */
    async setUserModelRaw(requestParameters: SetUserModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CopilotModelSelection>> {
        const requestOptions = await this.setUserModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CopilotModelSelectionFromJSON(jsonValue));
    }

    /**
     * Set User Model
     */
    async setUserModel(requestParameters: SetUserModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CopilotModelSelection> {
        const response = await this.setUserModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
