/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PolarionImportConfig,
    PolarionImportConfigFromJSON,
    PolarionImportConfigToJSON,
} from '../models/PolarionImportConfig';
import {
    type PolarionMetadataResponse,
    PolarionMetadataResponseFromJSON,
    PolarionMetadataResponseToJSON,
} from '../models/PolarionMetadataResponse';

/**
 * PolarionMetadataApi - interface
 * 
 * @export
 * @interface PolarionMetadataApiInterface
 */
export interface PolarionMetadataApiInterface {
    /**
     * Creates request options for getPolarionImportConfig without sending the request
     * @throws {RequiredError}
     * @memberof PolarionMetadataApiInterface
     */
    getPolarionImportConfigRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Polarion Import Config
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PolarionMetadataApiInterface
     */
    getPolarionImportConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolarionImportConfig>>;

    /**
     * Get Polarion Import Config
     */
    getPolarionImportConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolarionImportConfig>;

    /**
     * Creates request options for getPolarionSearchScopes without sending the request
     * @throws {RequiredError}
     * @memberof PolarionMetadataApiInterface
     */
    getPolarionSearchScopesRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Polarion Search Scopes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PolarionMetadataApiInterface
     */
    getPolarionSearchScopesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolarionMetadataResponse>>;

    /**
     * Get Polarion Search Scopes
     */
    getPolarionSearchScopes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolarionMetadataResponse>;

    /**
     * Creates request options for loadPolarionImportConfig without sending the request
     * @throws {RequiredError}
     * @memberof PolarionMetadataApiInterface
     */
    loadPolarionImportConfigRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Load Polarion Import Config
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PolarionMetadataApiInterface
     */
    loadPolarionImportConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolarionImportConfig>>;

    /**
     * Load Polarion Import Config
     */
    loadPolarionImportConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolarionImportConfig>;

}

/**
 * 
 */
export class PolarionMetadataApi extends runtime.BaseAPI implements PolarionMetadataApiInterface {

    /**
     * Creates request options for getPolarionImportConfig without sending the request
     */
    async getPolarionImportConfigRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/polarion-metadata/get-config`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Polarion Import Config
     */
    async getPolarionImportConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolarionImportConfig>> {
        const requestOptions = await this.getPolarionImportConfigRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PolarionImportConfigFromJSON(jsonValue));
    }

    /**
     * Get Polarion Import Config
     */
    async getPolarionImportConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolarionImportConfig> {
        const response = await this.getPolarionImportConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPolarionSearchScopes without sending the request
     */
    async getPolarionSearchScopesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/polarion-metadata/get-search-scopes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Polarion Search Scopes
     */
    async getPolarionSearchScopesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolarionMetadataResponse>> {
        const requestOptions = await this.getPolarionSearchScopesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PolarionMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get Polarion Search Scopes
     */
    async getPolarionSearchScopes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolarionMetadataResponse> {
        const response = await this.getPolarionSearchScopesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loadPolarionImportConfig without sending the request
     */
    async loadPolarionImportConfigRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/polarion-metadata/load-config`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Load Polarion Import Config
     */
    async loadPolarionImportConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolarionImportConfig>> {
        const requestOptions = await this.loadPolarionImportConfigRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PolarionImportConfigFromJSON(jsonValue));
    }

    /**
     * Load Polarion Import Config
     */
    async loadPolarionImportConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolarionImportConfig> {
        const response = await this.loadPolarionImportConfigRaw(initOverrides);
        return await response.value();
    }

}
