/* tslint:disable */
/* eslint-disable */
/**
 * Polragion Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChatHistoryMessage,
    ChatHistoryMessageFromJSON,
    ChatHistoryMessageToJSON,
} from '../models/ChatHistoryMessage';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type IngestResponse,
    IngestResponseFromJSON,
    IngestResponseToJSON,
} from '../models/IngestResponse';
import {
    type PolarionWorkItem,
    PolarionWorkItemFromJSON,
    PolarionWorkItemToJSON,
} from '../models/PolarionWorkItem';
import {
    type WorkItemAskResponse,
    WorkItemAskResponseFromJSON,
    WorkItemAskResponseToJSON,
} from '../models/WorkItemAskResponse';
import {
    type WorkItemSearchResponse,
    WorkItemSearchResponseFromJSON,
    WorkItemSearchResponseToJSON,
} from '../models/WorkItemSearchResponse';

export interface AskWorkItemRequest {
    prompt: string;
    projectId?: string | null;
    limit?: number | null;
    scoreThreshold?: number | null;
}

export interface IngestWorkItemsRequest {
    polarionWorkItem: Array<PolarionWorkItem>;
}

export interface IngestWorkItemsFromJsonDataSourceRequest {
    limit?: number | null;
}

export interface IngestWorkItemsFromPolarionDataSourceRequest {
    limit?: number | null;
}

export interface SearchWorkItemsRequest {
    prompt: string;
    projectId?: string | null;
    limit?: number | null;
    scoreThreshold?: number | null;
}

/**
 * WorkItemsApi - interface
 * 
 * @export
 * @interface WorkItemsApiInterface
 */
export interface WorkItemsApiInterface {
    /**
     * Creates request options for askWorkItem without sending the request
     * @param {string} prompt 
     * @param {string} [projectId] 
     * @param {number} [limit] 
     * @param {number} [scoreThreshold] 
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    askWorkItemRequestOpts(requestParameters: AskWorkItemRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Ask Work Item
     * @param {string} prompt 
     * @param {string} [projectId] 
     * @param {number} [limit] 
     * @param {number} [scoreThreshold] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    askWorkItemRaw(requestParameters: AskWorkItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkItemAskResponse>>;

    /**
     * Ask Work Item
     */
    askWorkItem(requestParameters: AskWorkItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkItemAskResponse>;

    /**
     * Creates request options for getChatHistory without sending the request
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    getChatHistoryRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Chat History
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    getChatHistoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatHistoryMessage>>>;

    /**
     * Get Chat History
     */
    getChatHistory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatHistoryMessage>>;

    /**
     * Creates request options for ingestWorkItems without sending the request
     * @param {Array<PolarionWorkItem>} polarionWorkItem 
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    ingestWorkItemsRequestOpts(requestParameters: IngestWorkItemsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Ingest Work Items
     * @param {Array<PolarionWorkItem>} polarionWorkItem 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    ingestWorkItemsRaw(requestParameters: IngestWorkItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngestResponse>>;

    /**
     * Ingest Work Items
     */
    ingestWorkItems(requestParameters: IngestWorkItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngestResponse>;

    /**
     * Creates request options for ingestWorkItemsFromJsonDataSource without sending the request
     * @param {number} [limit] 
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    ingestWorkItemsFromJsonDataSourceRequestOpts(requestParameters: IngestWorkItemsFromJsonDataSourceRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Ingest Work Items From Json Data Source
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    ingestWorkItemsFromJsonDataSourceRaw(requestParameters: IngestWorkItemsFromJsonDataSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngestResponse>>;

    /**
     * Ingest Work Items From Json Data Source
     */
    ingestWorkItemsFromJsonDataSource(requestParameters: IngestWorkItemsFromJsonDataSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngestResponse>;

    /**
     * Creates request options for ingestWorkItemsFromPolarionDataSource without sending the request
     * @param {number} [limit] 
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    ingestWorkItemsFromPolarionDataSourceRequestOpts(requestParameters: IngestWorkItemsFromPolarionDataSourceRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Ingest Work Items From Polarion Data Source
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    ingestWorkItemsFromPolarionDataSourceRaw(requestParameters: IngestWorkItemsFromPolarionDataSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngestResponse>>;

    /**
     * Ingest Work Items From Polarion Data Source
     */
    ingestWorkItemsFromPolarionDataSource(requestParameters: IngestWorkItemsFromPolarionDataSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngestResponse>;

    /**
     * Creates request options for resetUserSession without sending the request
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    resetUserSessionRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Reset User Session
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    resetUserSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     * Reset User Session
     */
    resetUserSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * Creates request options for searchWorkItems without sending the request
     * @param {string} prompt 
     * @param {string} [projectId] 
     * @param {number} [limit] 
     * @param {number} [scoreThreshold] 
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    searchWorkItemsRequestOpts(requestParameters: SearchWorkItemsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Search Work Items
     * @param {string} prompt 
     * @param {string} [projectId] 
     * @param {number} [limit] 
     * @param {number} [scoreThreshold] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkItemsApiInterface
     */
    searchWorkItemsRaw(requestParameters: SearchWorkItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkItemSearchResponse>>;

    /**
     * Search Work Items
     */
    searchWorkItems(requestParameters: SearchWorkItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkItemSearchResponse>;

}

/**
 * 
 */
export class WorkItemsApi extends runtime.BaseAPI implements WorkItemsApiInterface {

    /**
     * Creates request options for askWorkItem without sending the request
     */
    async askWorkItemRequestOpts(requestParameters: AskWorkItemRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prompt'] == null) {
            throw new runtime.RequiredError(
                'prompt',
                'Required parameter "prompt" was null or undefined when calling askWorkItem().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['prompt'] != null) {
            queryParameters['prompt'] = requestParameters['prompt'];
        }

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['scoreThreshold'] != null) {
            queryParameters['score_threshold'] = requestParameters['scoreThreshold'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/work-items/ask`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ask Work Item
     */
    async askWorkItemRaw(requestParameters: AskWorkItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkItemAskResponse>> {
        const requestOptions = await this.askWorkItemRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkItemAskResponseFromJSON(jsonValue));
    }

    /**
     * Ask Work Item
     */
    async askWorkItem(requestParameters: AskWorkItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkItemAskResponse> {
        const response = await this.askWorkItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getChatHistory without sending the request
     */
    async getChatHistoryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/work-items/ask/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Chat History
     */
    async getChatHistoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatHistoryMessage>>> {
        const requestOptions = await this.getChatHistoryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChatHistoryMessageFromJSON));
    }

    /**
     * Get Chat History
     */
    async getChatHistory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatHistoryMessage>> {
        const response = await this.getChatHistoryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestWorkItems without sending the request
     */
    async ingestWorkItemsRequestOpts(requestParameters: IngestWorkItemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['polarionWorkItem'] == null) {
            throw new runtime.RequiredError(
                'polarionWorkItem',
                'Required parameter "polarionWorkItem" was null or undefined when calling ingestWorkItems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/work-items/ingest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['polarionWorkItem']!.map(PolarionWorkItemToJSON),
        };
    }

    /**
     * Ingest Work Items
     */
    async ingestWorkItemsRaw(requestParameters: IngestWorkItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngestResponse>> {
        const requestOptions = await this.ingestWorkItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IngestResponseFromJSON(jsonValue));
    }

    /**
     * Ingest Work Items
     */
    async ingestWorkItems(requestParameters: IngestWorkItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngestResponse> {
        const response = await this.ingestWorkItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestWorkItemsFromJsonDataSource without sending the request
     */
    async ingestWorkItemsFromJsonDataSourceRequestOpts(requestParameters: IngestWorkItemsFromJsonDataSourceRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/work-items/ingest/import-json`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ingest Work Items From Json Data Source
     */
    async ingestWorkItemsFromJsonDataSourceRaw(requestParameters: IngestWorkItemsFromJsonDataSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngestResponse>> {
        const requestOptions = await this.ingestWorkItemsFromJsonDataSourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IngestResponseFromJSON(jsonValue));
    }

    /**
     * Ingest Work Items From Json Data Source
     */
    async ingestWorkItemsFromJsonDataSource(requestParameters: IngestWorkItemsFromJsonDataSourceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngestResponse> {
        const response = await this.ingestWorkItemsFromJsonDataSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestWorkItemsFromPolarionDataSource without sending the request
     */
    async ingestWorkItemsFromPolarionDataSourceRequestOpts(requestParameters: IngestWorkItemsFromPolarionDataSourceRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/work-items/ingest/import-polarion`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ingest Work Items From Polarion Data Source
     */
    async ingestWorkItemsFromPolarionDataSourceRaw(requestParameters: IngestWorkItemsFromPolarionDataSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngestResponse>> {
        const requestOptions = await this.ingestWorkItemsFromPolarionDataSourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IngestResponseFromJSON(jsonValue));
    }

    /**
     * Ingest Work Items From Polarion Data Source
     */
    async ingestWorkItemsFromPolarionDataSource(requestParameters: IngestWorkItemsFromPolarionDataSourceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngestResponse> {
        const response = await this.ingestWorkItemsFromPolarionDataSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resetUserSession without sending the request
     */
    async resetUserSessionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/work-items/reset`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reset User Session
     */
    async resetUserSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.resetUserSessionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Reset User Session
     */
    async resetUserSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.resetUserSessionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchWorkItems without sending the request
     */
    async searchWorkItemsRequestOpts(requestParameters: SearchWorkItemsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['prompt'] == null) {
            throw new runtime.RequiredError(
                'prompt',
                'Required parameter "prompt" was null or undefined when calling searchWorkItems().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['prompt'] != null) {
            queryParameters['prompt'] = requestParameters['prompt'];
        }

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['scoreThreshold'] != null) {
            queryParameters['score_threshold'] = requestParameters['scoreThreshold'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/work-items/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search Work Items
     */
    async searchWorkItemsRaw(requestParameters: SearchWorkItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkItemSearchResponse>> {
        const requestOptions = await this.searchWorkItemsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkItemSearchResponseFromJSON(jsonValue));
    }

    /**
     * Search Work Items
     */
    async searchWorkItems(requestParameters: SearchWorkItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkItemSearchResponse> {
        const response = await this.searchWorkItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
